//  Get all //

GET http://localhost:8081/password/all
Accept: application/json

> {%
client.test("Status kod je 200", function() {
    client.assert(response.status === 200, "Status kod nije 200, već je " + response.status);
 });

 client.test("Odgovor content-type je json", function() {
    var type = response.contentType.mimeType;
    client.assert(type === "application/json", "Očekivani format 'application/json' ali je odgovor '" + type + "'");
 });

 client.test("Da li je vraćen niz", function() {
   var type = response.body;
   client.assert(response.body instanceof Array, "Status kod nije 200, već je " + (typeof response.body) );
 });
%}

###

//  Get by ID //

GET http://localhost:8081/password?id=1
Accept: application/json

> {%

 client.test("Status kod je 200", function() {
    client.assert(response.status === 200, "Status kod nije 200, već je " + response.status);
 });


 %}

###


GET http://localhost:8081/password?id=5
Accept: application/json

> {%

 client.test("Status kod je 400", function() {
    client.assert(response.status === 400, "Status kod nije 400, već je " + response.status);
 });

 client.test("Ne postoji password sa id-om", function() {
    client.assert(response.body.message === "There is no password with id: 5");
 });


 %}

###


// Update password //
PUT http://localhost:8081/password
Content-Type: application/json

{
  "id":"1",
  "password":"novasifra111"
}

> {%
client.test("Status kod je 200", function() {
    client.assert(response.status === 200, "Status kod nije 200, već je " + response.status);
 });

 client.test("Sifra koja je dodata", function() {
    client.assert(response.body["password"] === "novasifra111", "Sifra je " + response.body["name"]);
 });
 %}

###

